### ISSUE TITLE
Fix get books list Problem

### ISSUE THREAD

**Issue by aminsamad** [loud-at-heart/books_sqflite#2]
Brother when I add new book and hot restart can't get book list after hot restart I get book list but can you create with offline ? without user and login.

**Comment by loud-at-heart** [comment]
The books are stored offline only
But since I am doing the user login using firebase authentication and want the books to be user specific the app has to want for couple of seconds to get email of the user and show the books

**Comment by aminsamad** [comment]
I am tried to remove user and firebase but didn't work.

**Comment by loud-at-heart** [comment]
Yes it will create some issue since the books which are coming are user specific and are called using the user email which is fetched from firebase
You can just change the firebase into sqflite and approach the same way ahead

**Comment by aminsamad** [comment]
Thanks but I don't know about backend 😅  I am just ui ux app designer

**Comment by loud-at-heart** [comment]
ok if possible I'll convert it and send you new repo

**Comment by aminsamad** [comment]
You are awesome brother thank you
